# Generated by Django 3.2.4 on 2021-06-04 07:31

import astrosat.utils.utils_db
from django.conf import settings
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('example', '0003_auto_20210422_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleConditionallyDeletedThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('should_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=functools.partial(astrosat.utils.utils_db.CONDITIONAL_CASCADE, *(), **{'condition': {'should_delete': True}, 'default_value': None}), related_name='things', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
