# Generated by Django 2.2.8 on 2020-03-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseLogRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('logger_name', models.CharField(max_length=128)),
                ('level', models.PositiveIntegerField(choices=[(0, 'NotSet'), (20, 'Info'), (30, 'Warning'), (10, 'Debug'), (40, 'Error'), (50, 'Fatal')], default=40)),
                ('message', models.TextField()),
                ('trace', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log Record',
                'verbose_name_plural': 'Log Records',
                'ordering': ('-created',),
            },
        ),
    ]
