# Generated by Django 3.0.4 on 2020-03-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat', '0002_databaselogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrosatsettings',
            name='enable_db_logging',
            field=models.BooleanField(default=False),
        ),
    ]
