# Generated by Django 3.0.4 on 2020-04-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat', '0003_astrosatsettings_enable_db_logging'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrosatsettings',
            name='enable_debug_toolbar',
            field=models.BooleanField(default=False, help_text='Show the django-debug-toolbar'),
        ),
    ]
