# Generated by Django 3.1.3 on 2020-11-11 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat', '0004_astrosatsettings_enable_debug_toolbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaselogrecord',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
