# Generated by Django 3.1.3 on 2020-11-12 11:09

import uuid
from django.db import migrations


def populate_uuids(apps, schema_editor):
    DatabaseLogRecordModel = apps.get_model('astrosat', 'DatabaseLogRecord')
    for model in DatabaseLogRecordModel.objects.all():
        model.uuid = uuid.uuid4()
        model.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat', '0005_databaselogrecord_uuid'),
    ]

    operations = [
        migrations.RunPython(
            populate_uuids, reverse_code=migrations.RunPython.noop
        )
    ]
