# Generated by Django 3.1.3 on 2020-11-12 11:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat', '0006_databaselogrecord_uuid_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaselogrecord',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
