# Generated by Django 3.1.3 on 2020-11-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat', '0007_databaselogrecord_uuid_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaselogtag',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
