# Generated by Django 3.2.4 on 2021-08-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrosat', '0009_auto_20210422_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaselogtag',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
